#include "char_to_hid_map.h"
// + character reserved for chorded keys

const char_hid_mapping_t modifier_mappings[] = {
    {'@', MOD_LEFT_CTRL},
    {'!', MOD_LEFT_SHIFT},
    {'#', MOD_LEFT_ALT},
    {'$', MOD_LEFT_GUI},
    {'%', MOD_RIGHT_CTRL},
    {'^', MOD_RIGHT_SHIFT},
    {'&', MOD_RIGHT_ALT},
    {'*', MOD_RIGHT_GUI},
};

const int modifier_mappings_count = sizeof(modifier_mappings) / sizeof(modifier_mappings[0]);

const char_hid_mapping_t character_mappings[] = {
    {'a', KEY_A},
    {'b', KEY_B},
    {'c', KEY_C},
    {'d', KEY_D},
    {'e', KEY_E},
    {'f', KEY_F},
    {'g', KEY_G},
    {'h', KEY_H},
    {'i', KEY_I},
    {'j', KEY_J},
    {'k', KEY_K},
    {'l', KEY_L},
    {'m', KEY_M},
    {'n', KEY_N},
    {'o', KEY_O},
    {'p', KEY_P},
    {'q', KEY_Q},
    {'r', KEY_R},
    {'s', KEY_S},
    {'t', KEY_T},
    {'u', KEY_U},
    {'v', KEY_V},
    {'w', KEY_W},
    {'x', KEY_X},
    {'y', KEY_Y},
    {'z', KEY_Z},

    {'0', KEY_0},
    {'1', KEY_1},
    {'2', KEY_2},
    {'3', KEY_3},
    {'4', KEY_4},
    {'5', KEY_5},
    {'6', KEY_6},
    {'7', KEY_7},
    {'8', KEY_8},
    {'9', KEY_9},

    {'W', KEY_UP},
    {'S', KEY_DOWN},
    {'D', KEY_RIGHT},
    {'A', KEY_LEFT},
    {'E', KEY_ENTER},
    {' ', KEY_SPACE},
    {'X', KEY_BACKSPACE},
    {'C', KEY_ESCAPE},
    {'V', KEY_TAB},
    {'Q', KEY_CAPSLOCK},
    {'Z', KEY_DELETE},
    {'M', KEY_PAGEUP},
    {'N', KEY_PAGEDOWN},
    {'F', KEY_END},

    {'R', KEY_F1},
    {'T', KEY_F2},
    {'Y', KEY_F3},
    {'U', KEY_F4},
    {'I', KEY_F5},
    {'O', KEY_F6},
    {'P', KEY_F7},
    {'H', KEY_F8},
    {'J', KEY_F9},
    {'K', KEY_F10},
    {'L', KEY_F11},
    {'B', KEY_F12},

    {',', KEY_COMMA},
    {'.', KEY_PERIOD},
    {'/', KEY_SLASH},
    {';', KEY_SEMICOLON},
    {'\'', KEY_QUOTE},
    {'`', KEY_GRAVE},
    {'[', KEY_LEFTBRACE},
    {']', KEY_RIGHTBRACE},
    {'\\', KEY_BACKSLASH},
    {'-', KEY_MINUS},
    {'=', KEY_EQUAL},
};

const int character_mappings_count = sizeof(character_mappings) / sizeof(character_mappings[0]);
