name: Build C Application

on:
  push:
  pull_request:

jobs:
  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive # pico-sdk submodule

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake build-essential

      - name: Configure and build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: build/

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MSYS2 and GCC
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
          msystem: MINGW64
          path-type: inherit

      - name: Configure and build
        shell: msys2 {0}
        run: |
          mkdir -p build
          cd build
          cmake -G "MinGW Makefiles" ..
          mingw32-make

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: build/
